import Head from "next/head";
import Layout from "../../components/layout";
const Contato = () => {
    return(<>
        <Head>
            <title>Contato</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
         <div className="container">
            sdadsads
        </div>
      </Layout>
    </>)
}
export default Contato