import Head from "next/head";
import Layout from "../../components/layout";
import * as Icon from "react-feather";
const Curriculo = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container">
          <div id="meucurriculo">
            <h2>Aline Pires Orozco</h2>
            <div className="dados">
              <h3>Dados Pessoais:</h3>
              <div>
                <strong>Disponível para mudança.</strong>
              </div>
              <div>
                <span> Celular : </span>
                <span>  <a href="tel:5515991979554"><Icon.PhoneCall size="13" /> (15) 99197 9554 </a> | <a href="https://wa.me/5515991979554">  <Icon.MessageCircle size="13" />  (15) 99197 9554 </a> </span>
              </div>
              <div>
                <span> E-mail : </span>
                <span> <a href="mail:alineorozco46@gmail.com">alineorozco46@gmail.com </a></span>
              </div>
              <div>
                <span> Idade : </span>
                <span> 36 anos </span>
              </div>
            </div>

            <div className="header">
              Área Administrativa, Recursos Humanos e Departamento pessoal
            </div>

            <div className="formacao">
              <h3>Formação</h3>
              <div className="item">
                Graduação em Gestão em Recursos Humanos - Faculdade Anhanguera
              </div>
              <div className="item">
                Especialização MBA Pós-graduação em Gestão de Pessoas -
                Faculdade Pitágoras
              </div>
              <div className="item">
                Especialização Practitioner em Programação Neurolinguística
                (PNL)
              </div>
              <div className="item">
                Formação em Analista Comportamental (DISC).
              </div>
            </div>
            <div className="histprof">
              <h3>Histórico profissional</h3>
              <div className="item">
                <p className="msg">
                  Fibratech Reciclagem Técnica Ltda (Grupo Trambusti) 06/2016 a
                  03/2021. ( Empresa grande porte na cidade de Porto Feliz - SP)
                </p>
                <p>
                  <strong>Cargo:</strong> Analista Recursos humanos e
                  departamento pessoal Generalista
                </p>
              </div>

              <div className="item">
                <p className="msg">
                  {" "}
                  Arruda Escritório de Contabilidade de Sorocaba ME - de 02/2015
                  a 12/2015. (Empresa de médio porte segmento contábil
                  Sorocaba).
                </p>
                <p>
                  <strong>Cargo:</strong>Cargo: Analista de recursos humanos
                  generalista.
                </p>
              </div>

              <div className="item">
                <p className="msg">
                  Formtap Indústria e Comércio S.A - de 06/2012 a 01/2015.
                  (Grupo Trambusti (Empresa acima de 1500 funcionários grande
                  porte segmento automotivos Sorocaba).
                </p>
                <p>
                  <strong>Cargo:</strong> Assistente de recursos humanos.
                </p>
              </div>

              <div className="item">
                <p className="msg">
                  {" "}
                  Automatic House Automação Residencial - de janeiro/2012 a
                  junho/2012.(Empresa de médio porte segmento construção civil).
                  Cargo: Estagiária RH
                </p>
              </div>
            </div>
            <div className="experiencia">
              <div className="header">
                Experiências anteriores como Assistente Administrativa
                totalizando 18 anos em CTPS.
              </div>
              <p>
                Possuo 10 (Dez) anos de experiência no setor de Recursos
                Humanos. Atuando diretamente com subsistemas, provisão de
                recursos, aplicação, manutenção, desenvolvimento e monitoramento
                de pessoas.
              </p>
              <p>
                Responsável pela implementação de políticas de Recursos Humanos.
                Processo de recrutamento e seleção de vagas operacionais em
                grande escala, administrativas e gerenciais.
              </p>
              <i>
                Atuando ativamente na gestão dos KPIS do setor e no plano de
                ação
              </i>
              <p>
                Experiência em treinamento e desenvolvimento de equipes,
                implantação no processo da certificação e recertificação da
                ISO/IATF 16949:2016, ISO 14001:2015, ISO 9001:2015. E no
                treinamento interno e externo para implantação Sistema 5S e
                desenvolvimento de Liderança. Responsável pela integração e
                reintegração e treinamento na garantia do cumprimento dos
                procedimentos internos. Responsável pela comunicação interna e
                motivacional.
              </p>
              <p>
                Administração de benefícios como vale transporte, vale
                alimentação, restaurante na empresa, fretado , convênio médico,
                odontológico e entre outros.
              </p>
              <p>
                Responsável pela rotina do departamento pessoal e da folha de
                pagamento. Experiência e domínio no Sistema Integrado DataSul
                TOTVS, Henry e TSA.
              </p>
              <p>
                Atuando com cálculos e conferência da folha de pagamento.
                Lançamentos de débitos e créditos, 13° salário, benefícios,
                rescisões e homologações. admissões, férias, encargos sindicais,
                emissões de guias para pagamento GRRF, GPS, DARF, Encargos
                Sociais (RAIS, DIRF, SEFIP, CAGED), conectividade social (ICP),
                apuração e apontamento eletrônico e manual, administração das
                convenções coletivas. Implantação do e-social e integração do
                sistema na folha.
              </p>
              <p>
                Preposta da empresa para audiência trabalhista. Responsável nos
                atendimentos, processos de auditorias de clientes e
                certificações.
              </p>
              <div className="header">Informações complementares</div>
              <p>
                Na busca de recursos e ferramentas para aplicabilidade nos
                processos, procedimentos e na geração de resultados. Cursos de
                atualização na Gestão de Pessoas.
              </p>

              <ul>
                <li>
                  <Icon.ChevronsRight size="13" /> Maratona Departamento Pessoal 2020 ( e-social) – EB
                  treinamento
                </li>
                <li>
                  <Icon.ChevronsRight size="13" /> Treinamento Sistema Toyota de
                  Produção – Toyota
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  Auditor ISO14001:2015 - SGS Group
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  Auditor ISO/IATF:2016 - SGS Group
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  Treinamento ISO/IATF:2016 - SGS Group
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  Treinamento ISO 9001:2015 - SGS Group
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  Palestra Assédio Moral no Ambiente de Trabalho – Benício
                  Advogados
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  Treinamento de liderança - Sesi
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  Auditor 5S’s – Senai
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  Treinamento 5S’s - Senai
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  SOGI – Sistema Online de Gestão Integrada – Processos
                  Ambientais ISO 14001
                </li>
                <li>
                  <Icon.ChevronsRight size="13" />
                  *Inglês – Intermediário cursando*
                </li>
              </ul>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};
export default Curriculo;
